%april7_2020
clear;

%%
cd ~/products/rsam/;

%%
%"AMAC";"GYPL";"GYPS";"GYGU";"GYKA";"GYZU";"AMNT";"ASDO";"ACUE";"ARIO";"APO2";"ALJ1";...
%    "GYE1";"GYE3";"AC07";"ABH2";"ABH3";"ACHN";"ALAT";"ASLC";"APJL";"AAM2";"ABAB";
%kstnm = ["APUY";"ACOT";"AAT1";"AOTA"];
% kstnm = ["BNAS";"BV15";"PVIL";"ALCE";"PPLP";"CHMA";"LNGL";"ZUMB";"BOSC";"MILO";"CAB1";...
%     "ZUMB";"ANGU";"ARNL";"MORR";"ANTS";"ANTG";"ANTM";"SALI";"SNLR";"SUSE";"TAIS";...
%     "TAMH";"PORT";"PCRA";"COHC";"MCRA";"ILLI";"GONZ";"LAMO";"ISPG";"JSCH";"JIPI";...
%     "CHSH";"COTA";"CASC";"CUSE";"CUSW";"CSOL";"CUIC";"IMBA";"PAC1";"PIAT";"PIS1";"PKYU"];

%% HHZ
kstnm = ["ALAU";"ATEN";"ARDO";"ESM1";"MONB";"ANTC";"AIMS";"BALZ";"RVRD";"PTGL"];

for i = 1:length(kstnm)
    kstnm_ = kstnm(i);
    S = rmsGather(datetime(2006,01,01),dn2dt(floor(now)),60,1,8,string(kstnm_),"HHZ",0,1,"EC","",0,1);
    save(strcat('EC.',kstnm_,'..HHZ_1Hz8Hz_60DUR_VEL_RMS_SLIDEMED_MedPreFilt3Points.mat'));
end

%% SHZ
kstnm = ["LITA";"PITA"];

for i = 1:length(kstnm)
    kstnm_ = kstnm(i);
    S = rmsGather(datetime(2006,01,01),dn2dt(floor(now)),60,1,8,string(kstnm_),"SHZ",0,1,"EC","",0,1);
    save(strcat('EC.',kstnm_,'..SHZ_1Hz8Hz_60DUR_VEL_RMS_SLIDEMED_MedPreFilt3Points.mat'));
end

%% HNZ
kstnm = ["AATC";...
    "ACH1";...
    "ACH2";...
    "AES2";...
    "AGRD";...
    "AIB2";...
    "AIMS";...
    "ALBE";...
    "ALIT";...
    "ALOR";...
    "AMA1";...
    "AMCR";...
    "AMIL";...
    "ANTC";...
    "APLA";...
    "APLP";...
    "APR2";...
    "APS1";...
    "APS4";...
    "APSY";...
    "AQUE";...
    "ARNL";...
    "ATEN";...
    "ATLC";...
    "ATUL";...
    "AV03";...
    "AV05";...
    "AV18";...
    "AV21";...
    "AVX7";...
    "AZAM";...
    "AZOG";...
    "BALZ";...
    "BONI";...
    "BOSC";...
    "CAB1";...
    "CAYA";...
    "CHMA";...
    "CRPG";...
    "ELAR";...
    "ESM1";...
    "GBMB";...
    "GYC2";...
    "IESS";...
    "ISPG";...
    "ISPT";...
    "LAMO";...
    "LNGL";...
    "PARU";...
    "PTGL";...
    "RVRD";...
    "SALI";...
    "ZALD";...
    "ZUMB"];

for i = 1:length(kstnm)
    kstnm_ = kstnm(i);
    S = rmsGather(datetime(2006,01,01),dn2dt(floor(now)),60,1,8,string(kstnm_),"HNZ",0,1,"EC","",0,1);
    save(strcat('EC.',kstnm_,'..HNZ_1Hz8Hz_60DUR_ACC_RMS_SLIDEMED_MedPreFilt3Points.mat'));
end

