% november17_2019
% this is code specifically for clint (susans student)
clear; close all; clc;

%%
cd ~/igdata/velocityModels/
load iasp91_1km800Depth_10km20000dist.mat
[X,Y] = meshgrid(dists,depths);
rawDataDir = '~/rawdata/'; %'~/data/iguana/BROADBAND/';
writeSacFlag = true;

%%
cd ~/research/favors/clint/
load EAE2.txt
t = datetime(EAE2(:,1),EAE2(:,2),EAE2(:,3),EAE2(:,4),EAE2(:,5),EAE2(:,6));
[t,tI] = sort(t);
eqlat = EAE2(tI,7);
eqlon = EAE2(tI,8);
eqdepth = EAE2(tI,9);

%%
% tI = t <= datetime(2015,01,01);
% t = t(tI);
% eqlat = eqlat(tI);
% eqlon = eqlon(tI);
% eqdepth = eqdepth(tI);

%%
% masterList = ["VCH1","9D","HH","";...
%     "SN01","9D","HH","";...
%     "SN02","9D","HH","";...
%     "SN03","9D","HH","";...
%     "SN04","9D","HH","";...
%     "SN05","9D","HH","";...
%     "SN06","9D","HH","";...
%     "SN07","9D","HH","";...
%     "SN08","9D","HH","";...
%     "SN09","9D","HH","";...
%     "SN10","9D","HH","";...
%     "SN11","9D","HH","";...
%     "SN12","9D","HH","";...
%     "SN13","9D","HH","";...
%     "SN14","9D","HH",""];

masterList = ["CASC","EC","HH","";...
    "ARDO","EC","HH","";...
    "PUYO","EC","HH","";...
    "PKYU","EC","HH","";...
    "TAIS","EC","HH","";...
    "BOSC","EC","HH","";...
    "TAMH","EC","HH","";...
    "TOMA","EC","BH","";...
    "SUCR","EC","BH","";...
    "SRAM","EC","BH","";...
    "BRRN","EC","BH","";...
    "PIAT","EC","HH","";...
    "PAC1","EC","HH","";...
    "BULB","EC","BH","";...
    "PINO","EC","SH","";...
    "BREF","EC","BH","";...
    "BNAS","EC","BH","";...
    "BMAS","EC","BH","";...
    "BRTU","EC","HH","";...
    "ANGU","EC","HH","";...
    "ANTM","EC","HH","";...
    "ANTS","EC","HH","";...
    "ANTG","EC","HH","";...
    "ANTC","EC","HH","";...
    "BTER","EC","HH","";...
    "GGPC","EC","HH","";...
    "GGPT","EC","HH","";...
    "COHC","EC","HH","";...
    "CHSH","EC","HH","";...
    "CHL1","EC","HH","";...
    "CHL2","EC","HH","";...
    "CHMA","EC","HH","";...
    "COTA","EC","HH","";...
    "CUIC","EC","HH","";...
    "BIL2","EC","SH","";...
    "LNGL","EC","HH","";...
    "BBIL","EC","BH","";...
    "ARA2","EC","HH","";...
    "CAYR","EC","SH","";...
    "CAYA","EC","HH","";...
    "BPAT","EC","BH","";...
    "BRUN","EC","BH","";...
    "BTAM","EC","BH","";...
    "BVC2","EC","BH","";...
    "PINO","EC","SH","";...
    "PECV","EC","SH","";...
    "LITA","EC","SH","";...
    "JAMA","EC","SH","";...
    "BONI","EC","HH","";...
    "TULM","EC","HH","";...
    "TERV","EC","SH","";...
    "LAV4","EC","SH","";...
    "BMOR","EC","BH","";...
    "VCES","EC","HH","";...
    "URCU","EC","HH","";...
    "CUSE","EC","HH","";...
    "CUSW","EC","HH","";...
    "YAHU","EC","HH","";...
    "GONZ","EC","HH","";...
    "ZUMB","EC","HH","";...
    "MCRA","EC","HH",""];

%%
stnms = masterList(:,1);
nets = masterList(:,2);
chans = masterList(:,3);
locs = masterList(:,4);

[stla,stlo] = metaDataFromStationList(stnms);
goodI = isfinite(stla);
stnms = stnms(goodI);
nets = nets(goodI);
chans = chans(goodI);
locs = locs(goodI);

%%
noiseWin = seconds(20);
signalWin = seconds(100);

%%
newDir = '~/public_html/PRFEcuador/'; %'~/research/favors/clint/sac/';
if ~exist(newDir,'dir')
    mkdir(newDir)
end

%%
refEllipse = referenceEllipsoid('wgs84');
parfor i = 1:length(stla)
    stla_ = stla(i);
    stlo_ = stlo(i);
    stnm_ = stnms(i);
    net_ = nets(i);
    chans_ = chans(i);
    locs_ = locs(i);
    d = distance(stla(i),stlo(i),eqlat,eqlon,refEllipse)*1e-3;
    
    tic;
    tt = interp2(X,Y,travTimes,d,eqdepth,'spline');
    toc;
    
    Scut = extractWaveforms(t + seconds(tt) - noiseWin,noiseWin+signalWin,...
        stnm_,[strcat(chans_,"Z");strcat(chans_,"N");strcat(chans_,"E")],...
        net_,locs_,false,true);
    refs = pull(Scut(:,1),'ref');
    goodI = ~isnat(refs);
    refs = refs(goodI);
    Scut = Scut(goodI,:);
    
    %% here i write to sac file
    if writeSacFlag
        t_ = t(goodI);
        eqlat_ = eqlat(goodI);
        eqlon_ = eqlon(goodI);
        eqdepth_ = eqdepth(goodI);
        for j = 1:sum(goodI)
            eventDir = strcat('Event_',datestr(t_(j),'yyyy.mm.dd.HH.MM.SS'));
            if ~exist(strcat(newDir,'/',eventDir),'dir')
                mkdir(strcat(newDir,'/',eventDir));
            end
            
            ref_ = refs(j);
            kstnm_ = Scut(j,1).kstnm;
            knetwk_ = Scut(j,1).knetwk;
            khole_ = Scut(j,1).khole;
            for k = 1:3
                if isnat(Scut(j,k).ref)
                    % skip if no data
                    continue;
                end
                
                %%
                kcmpnm_ = Scut(j,k).kcmpnm;
                fileName = [char(kstnm_),'.',char(knetwk_),'.',char(khole_),'.',...
                    char(kcmpnm_),'.',datestr(ref_,'yyyy.mm.dd.HH.MM.SS.FFF'),'.SAC'];
                
                disp(['attempting to write: ',fileName])
                mksac(strcat(newDir,'/',eventDir,'/',fileName),...
                    Scut(j,k).d,...
                    datenum(Scut(j,k).ref),...
                    'DELTA',Scut(j,k).delta,...
                    'KSTNM',kstnm_,...
                    'KCMPNM',kcmpnm_,...
                    'KNETWK',knetwk_,...
                    'LCALDA',true,...
                    'STLA',stla_,...
                    'STLO',stlo_,...
                    'EVLA',eqlat_(j),...
                    'EVLO',eqlon_(j),...
                    'EVDP',eqdepth_(j)*1e3); %eqdepth is in meters
            end
        end
    end
end
