clear; 
close all; 
load("CotopaxiVLPWaveformsBREF_v1");
SHOR = scaleWaveforms(resampleWaveforms(detrendWaveforms(extractWaveforms(tMain,...
    seconds(60),...
    ["CO1V";"BREF";"BVC2";"BTAM";"BMOR";"BNAS"],...
    ["BHZ";"BHN";"BHE";"HHZ";"HHN";"HHE"],"EC","",true,true,...
1,true,[0.2,0.8,false,true,false])),10),1e9);
save("CotopaxiVLPWaveformsBREF_v1",...
    "SHOR","tMain","ccMain","madMain","nUsedMain",...
    "dMag","magMain","templateNumber","highAmps","lowAmps");