function [lon,lat,demData] = loadNamedDEM(regionName)
lon = [];
lat = [];
demData = [];

%%
if strcmp(regionName,'guagua') || strcmp(regionName,'cotopaxi') ...
        || strcmp(regionName,'tungurahua') || strcmp(regionName,'reventador') ...
        || strcmp(regionName,'chiles') || strcmp(regionName,'cuicocha') ...
        || strcmp(regionName,'pichincha') || strcmp(regionName,'quito') ...
        || strcmp(regionName,'cayambe') || strcmp(regionName,'sangay') ...
        || strcmp(regionName,'pululahua') || strcmp(regionName,'chimborazo') ...
        || strcmp(regionName,'antisana') || strcmp(regionName,'quilotoa')
    demName = strcat('~/igdata/dem/',regionName,'_dem');
    load(demName,'lon','lat','demData');
elseif strcmp(regionName,'ecuador-continental') || strcmp(regionName,'ecuador') ...
        || strcmp(regionName,'costa') || strcmp(regionName,'esmeraldas') ...
        || strcmp(regionName,'punta-galera') || strcmp(regionName,'atacames') ...
        || strcmp(regionName,'puna') || strcmp(regionName,'balao') ...
        || strcmp(regionName,'pisayambo') || strcmp(regionName,'manta') ...
        || strcmp(regionName,'plata') || strcmp(regionName,'outer-rise') ...
        || strcmp(regionName,'jama') || strcmp(regionName,'pedernales')
    boundaryBox = getRegionSpatialDimensions(regionName);
    [lon,lat,demData] = cutDEM(boundaryBox);
elseif strcmp(regionName,'wolf') || strcmp(regionName,'sierra-negra') ...
        || strcmp(regionName,'cerro-azul') || strcmp(regionName,'alcedo') ...
        || strcmp(regionName,'darwin') || strcmp(regionName,'fernandina') ...
        || strcmp(regionName,'galapagos') || strcmp(regionName,'bahia-elizabeth')
    boundaryBox = getRegionSpatialDimensions(regionName);
    minLon = boundaryBox(1);
    maxLon = boundaryBox(2);
    minLat = boundaryBox(3);
    maxLat = boundaryBox(4);
    load('~/igdata/dem/galapagos_dem.mat','lat','lon','demData');
    lonI = lon >= minLon & lon <= maxLon;
    latI = lat >= minLat & lat <= maxLat;
    lon = lon(lonI);
    lat = lat(latI);
    demData = demData(latI,lonI);
else
    disp('sorry, no region with that name found.')
end