function sacwrite(fileName,S)

%
% sacwrite(fileName,S)
%

%%
S = S(1);
%         S1.evla = origlat;
%         S1.evlo = origlon;
%         S1.evdp = origdepth;
%         S1.dist = d_(i);
%         S1.az = azs(i);
%         S1.baz = bazs(i);
%         S1.gcarc = km2deg(d_(i));
%         S1.user0 = Pphases(i).t;        % analyst's p-pick

mksac(fileName,S.d,datenum(S.ref),...
    'DELTA',S.delta,...
    'KSTNM',S.kstnm,...
    'KCMPNM',S.kcmpnm,...
    'KNETWK',S.knetwk,...
    'KHOLE',S.khole,...
    'EVLA',S.evla,...
    'EVLO',S.evlo,...
    'EVDP',S.evdp,...
    'DIST',S.dist,...
    'MAG',S.eqmag,...
    'AZ',S.az,...
    'BAZ',S.baz,...
    'GCARC',S.gcarc,...
    'USER0',datenum(S.user0));