cd ~;
eventIDs = "igepn2016hnmu";

% eventIDs = [
%     "igepn2016fgfa";...
%     "igepn2016pocw";...
%     "igepn2016rldl";...
%     "igepn2018gmes";...
%     "igepn2014qbvj";...
%     "igepn2014pund";...
%     "igepn2014yydb";...
%     "igepn2016abic";...
%     "igepn2018ynla";...
%     "igepn2016hnmu";...
%     "igepn2016jste";...
%     "igepn2015kmsr";...
%     "igepn2016yvmv";...
%     "igepn2016wich";...
%     "igepn2018lpjt";...
%     "igepn2018ebfc"];

hfc = 40;
npoles = 4;

% eventIDs = ["igepn2014psys";... %cant read file
%     "igepn2016fgfa";...
%     "igepn2016pocw";...
%     "igepn2016rldl";...
%     "igepn2018gmes";...
%     "igepn2014qbvj";...
%     "igepn2014pund";...
%     "igepn2014yydb";...
%     "igepn2016abic";...
%     "igepn2018ynla";...
%     "igepn2021wyvu";... %does not exist
%     "igepn2016hnmu";...
%     "igepn2016jste";...
%     "igepn2015kmsr";...
%     "igepn2016yvmv";...
%     "igepn2018rncq";... %does not exist
%     "igepn2023fkei";... %does not exist
%     "igepn2020vdrd";... %does not exist
%     "igepn2016wich";...
%     "igepn2022mnsv";... %does not exist
%     "igepn2014ptqc";... %cant read file
%     "igepn2018lpjt";...
%     "igepn2018ebfc";...
%     "igepn2018rgju";... %does not exist
%     "igepn2013qals";... %does not exist
%     "igepn2014xzkf"]; %cant read file

for i = 1:length(eventIDs)
    eventID_ = eventIDs(i);
    yyyy = char(eventID_);
    yyyy = yyyy(6:9);
    files = dir(strcat('~/products/EcuadorStrongMotion/',yyyy,'/*/',eventID_,'*/AmplitudeVsDistance_DISP.png'));
    lfiles = length(files);

%     if lfiles > 0
%         fprintf('already processed %s, skipping...\n',eventID_);
%         continue;
%     else
%         fprintf('will process: <strong>%s</strong>\n',eventID_);
%     end

    try
        writeStrongMotionRecords(eventID_,5,10,1/40,hfc,npoles,'acc');
    catch
        fprintf(2,'something went wrong\n');
        continue;
    end

%     try
%         writeStrongMotionRecords(eventID_,5,10,1/10,hfc,npoles,'vel');
%     catch
%         fprintf(2,'something went wrong\n');
%         continue;
%     end
% 
%     try
%         writeStrongMotionRecords(eventID_,5,10,1/5,hfc,npoles,'disp');
%     catch
%         fprintf(2,'something went wrong\n');
%         continue;
%     end
end
