clear; close all; clc;

%% seed the original data
Sorig = seedData();

%%
updateGlobalCatalog();

%% %updateHelicorders
% snclList = [...
%     "SAGA" "HHZ" "EC" "";...
%     "SAGA" "BDF" "EC" "01";...
%     "PUYO" "HHZ" "EC" "";...
%     "TAIS" "HHZ" "EC" "";...
%     "PKYU" "HHZ" "EC" "";...
%     "TAMH" "HHZ" "EC" "";...
%     "BPAT" "BHZ" "EC" "";..
%     "BMAS" "BHZ" "EC" "";...
%     "BULB" "BHZ" "EC" "";...
%     "BRUN" "BHZ" "EC" "";...
%     "PORT" "HHZ" "EC" "";...
%     "REVS" "HHZ" "EC" "";...
%     "REVS" "BDF" "EC" "01";...
%     "REVN" "HHZ" "EC" "";...
%     "REVN" "BDF" "EC" "01";...
%     "CASC" "HHZ" "EC" "";...
%     "CAYR" "SHZ" "EC" "";...
%     "BMOR" "BHZ" "EC" "";...
%     "BNAS" "BHZ" "EC" "";...
%     "BREF" "BHZ" "EC" "";...
%     "BTAM" "BHZ" "EC" "";...
%     "BVC2" "BHZ" "EC" "";...
%     "NAS2" "SHZ" "EC" "";...
%     "TAMB" "SHZ" "EC" "";...
%     "VC1" "SHZ" "EC" "";...
%     "FER1" "BHZ" "EC" "";...
%     "FER2" "HHZ" "EC" "";...
%     "VCH1" "HHZ" "EC" "";...
%     "PVIL" "HHZ" "EC" "";...
%     "CEAZ" "BHZ" "EC" "";...
%     "ALCE" "HHZ" "EC" "";...
%     ];