function S = populatePoleZeroStruct(N)
if nargin < 1; N = 1; end
S.zeros = NaN;
S.poles = NaN;
S.constant = NaN;
S.knetwk = NaN;
S.kstnm = NaN;
S.khole = NaN;
S.kcmpnm = NaN;
S.tStart = NaT;
S.tEnd = NaT;
S.stla = NaN;
S.stlo = NaN;
S.stel = NaN;
S.stde = NaN;
S.stdi = NaN;
S.staz = NaN;
S.Fs = NaN;
S.instType = NaN;
S.instGain = NaN;
S.sensitivity = NaN;
S.a0 = NaN;
S = repmat(S,N,1);