function [E,t,origlat,origlon,origdepth,origmag,...
    origtimerr,origlonerr,origlaterr,origdeptherr,origmagerr,...
    nPphases,nSphases,origrms,origgap,...
    nMLv,nML,nMjma,nMsBB,nMwp,nmB,nmb,ids,usedPhases] = extractSC3Catalog(tStart,tEnd,minLon,maxLon,minLat,maxLat,minMag,maxDepth)

[t,eqlat,eqlon,eqdepth,eqmag,ids] = readCat1(); %2000,01,01,2019,12,31,-10);
dI = t >= tStart & t < tEnd ...
    & eqlat >= minLat & eqlat <= maxLat & eqlon >= minLon & eqlon <= maxLon ...
    & eqdepth <= maxDepth & (eqmag >= minMag | eqmag == -999);

%%
ids = string(ids(dI));
[E,t,origlat,origlon,origdepth,origmag,...
    origtimerr,origlonerr,origlaterr,origdeptherr,origmagerr,...
    nPphases,nSphases,origrms,origgap,...
    nMLv,nML,nMjma,nMsBB,nMwp,nmB,nmb,ids,usedPhases] = extractSC3CatalogFromList(ids,0);